# Connexió a db-aules
spring.datasource.type=org.springframework.jdbc.datasource.DriverManagerDataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.jdbcUrl=jdbc:postgresql://db-aules.uji.es:5432/ei102725omf
spring.datasource.username=ei102725omf
spring.datasource.password=ei102725omf

# Logging
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

# Sessió (en minuts)
server.servlet.session.timeout=30